import 'dart:convert';
import 'dart:math';

import 'package:flutter/material.dart';
import 'package:flutter/services.dart';

class Questions {
  // Private constructor to prevent external instantiation.
  Questions._internal();

  // Private instance variable for the single instance.
  static final Questions _instance = Questions._internal();

  // Public factory method to access the instance.
  factory Questions() {
    return _instance;
  }

  // Add your methods and properties here.
  List<Q>? trivia;
  bool _loaded = false;

  // Autogenerated
  void _fromJson(Map<String, dynamic> json) {
    if (json['questions'] != null) {
      trivia = <Q>[];
      json['questions'].forEach((v) {
        trivia!.add(Q.fromJson(v));
      });
    }
  }

  void load() async {
    String string = await rootBundle.loadString('assets/trivia_data.json');
    try {
      final Map<String, dynamic> data = json.decode(string);
      _fromJson(data);
      _loaded = true;
    } on Exception catch (e) {
      debugPrint(e.toString());
    }
  }

  /// Get a random question
  Q getQuestion() {
    Random random = Random();
    int rand = random.nextInt(trivia!.length);
    return trivia![rand];
  }
}

class Q {
  String? category;
  String? type;
  String? difficulty;
  String? question;
  String? correctAnswer;
  List<String>? incorrectAnswers;

  Q({
    this.category,
    this.type,
    this.difficulty,
    this.question,
    this.correctAnswer,
    this.incorrectAnswers,
  });

  Q.fromJson(Map<String, dynamic> json) {
    category = json['category'];
    type = json['type'];
    difficulty = json['difficulty'];
    question = json['question'];
    correctAnswer = json['correct_answer'];
    incorrectAnswers = json['incorrect_answers'].cast<String>();
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = <String, dynamic>{};
    data['category'] = category;
    data['type'] = type;
    data['difficulty'] = difficulty;
    data['question'] = question;
    data['correct_answer'] = correctAnswer;
    data['incorrect_answers'] = incorrectAnswers;
    return data;
  }
}
